basePath: /api
definitions:
  models.BudgetItemDTO:
    properties:
      amount:
        type: number
      covered:
        type: number
      id:
        type: integer
      name:
        type: string
      recurrence:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample API for a budgeting application.
  termsOfService: http://swagger.io/terms/
  title: Budgeting API
  version: "1.0"
paths:
  /api/budget-items:
    get:
      consumes:
      - application/json
      description: Retrieve all budget items from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.BudgetItemDTO'
            type: array
      summary: Get all budget items
      tags:
      - Budget Items
    post:
      consumes:
      - application/json
      description: Create a new budget item in the database
      parameters:
      - description: Budget Item
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/models.BudgetItemDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.BudgetItemDTO'
      summary: Create a new budget item
      tags:
      - Budget Items
  /api/budget-items/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a budget item from the database
      parameters:
      - description: Budget Item ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Item deleted
          schema:
            type: string
      summary: Delete a budget item
      tags:
      - Budget Items
    get:
      consumes:
      - application/json
      description: Retrieve a specific budget item by ID
      parameters:
      - description: Budget Item ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.BudgetItemDTO'
      summary: Get a specific budget item
      tags:
      - Budget Items
    put:
      consumes:
      - application/json
      description: Update a budget item in the database
      parameters:
      - description: Budget Item ID
        in: path
        name: id
        required: true
        type: integer
      - description: Budget Item
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/models.BudgetItemDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.BudgetItemDTO'
      summary: Update a budget item
      tags:
      - Budget Items
swagger: "2.0"
