name: Go CI

on:
  push:
    branches:
      - develop
      - feature/*
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Install dependencies
      run: go mod tidy

    - name: Run Lint
      run: go vet ./...

    - name: Run Tests
      run: go test ./... -cover